// ==UserScript==
// @name         TiRex Bypass - Last Update
// @namespace    http://tampermonkey.net/
// @version      1.2.7.0
// @description  Bypass Work.ink links
// @author       Difzz
// @match        https://work.ink/*
// @match        https://*.work.ink/*
// @match        https://workink.net/*
// @match        https://*.workink.net/*
// @match        https://yub-x.net/*
// @match        https://links.lootlabs.gg/*
// @match        https://loot-link.com/*
// @match        https://lootlinks.co/*
// @match        https://loot-links.com/*
// @match        https://lootdest.com/*
// @match        https://lootlink.org/*
// @match        https://lootdest.info/*
// @match        https://lootdest.org/*
// @match        https://links-loot.com/*
// @match        https://linksloot.net/*
// @match        https://best-links.org/*
// @match        https://loot-labs.com/*
// @match        https://lootlabs.com/*
// @match        https://tpi.li/*
// @match        https://*.tpi.li/*
// @match        https://draculahub.xyz/*
// @match        https://rekonisefromtemu.pages.dev/*
// @match        https://bstshrt.com/*
// @match        https://rekonise.com/*
// @match        https://sub4unlock.co/*
// @match        https://link-unlock.com/*
// @match        https://subnise.com/*
// @match        https://bstlar.com/*
// @match        https://sub2unlock.io/*
// @match        https://socialwolvez.com/*
// @match        https://dusarisalary.com/*
// @match        https://app.khaddavi.net/*
// @match        https://spdmteam.com/*
// @match        https://linkvertise.com/*
// @match        https://linkvertise.net/*
// @match        https://link-to.net/*
// @match        https://admaven.com/*
// @match        https://shortearn.eu/*
// @match        https://cuty.io/*
// @match        https://ouo.io/*
// @match        https://lockr.so/*
// @match        https://mboost.me/*
// @match        https://hydrogen.lat/*
// @match        https://auth.platorelay.com/*
// @match        https://pandadevelopment.net/*
// @run-at       document-start
// @grant        unsafeWindow
// @downloadURL  https://github.com/Difz25x/bypass/raw/refs/heads/main/workink.user.js
// @updateURL    https://github.com/Difz25x/bypass/raw/refs/heads/main/workink.user.js
// @require      https://github.com/Difz25x/bypass/raw/refs/heads/main/workink-bypass.js
// ==/UserScript==
